{{- if .Values.oauth2Proxy.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "feedbox.fullname" . }}-oauth2-proxy
  labels:
    {{- include "feedbox.labels" . | nindent 4 }}
    app.kubernetes.io/component: oauth2-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "feedbox.name" . }}-oauth2-proxy
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "feedbox.name" . }}-oauth2-proxy
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ include "feedbox.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: oauth2-proxy
        image: "{{ .Values.oauth2Proxy.image.repository }}/{{ .Values.oauth2Proxy.image.name }}:{{ .Values.oauth2Proxy.image.tag }}"
        imagePullPolicy: {{ .Values.oauth2Proxy.image.pullPolicy }}
        command: ["/bin/sh"]
        args:
          - -c
          - |
            /bin/oauth2-proxy \
            --provider={{ .Values.oauth2Proxy.config.provider }} \
            --oidc-issuer-url={{ .Values.oauth2Proxy.config.oidcIssuerUrl }} \
            --email-domain={{ join "," .Values.oauth2Proxy.config.emailDomains }} \
            --upstream=http://{{ include "feedbox.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.service.port }} \
            --http-address=0.0.0.0:4180 \
            --cookie-secure={{ .Values.oauth2Proxy.config.cookieSecure | quote }} \
            --redirect-url={{ .Values.oauth2Proxy.config.redirectUri }} \
            --client-id={{ .Values.oauth2Proxy.config.clientId }} \
            --client-secret=$(cat /etc/secrets/client_secret) \
            --cookie-secret=$(cat /etc/secrets/cookie_secret) \
            --skip-provider-button=true \
            --code-challenge-method=S256 \
        volumeMounts:
        - name: secrets
          mountPath: /etc/secrets
          readOnly: true
        ports:
          - containerPort: 4180
            name: proxy
        resources:
          requests:
            cpu: 20m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
          readOnlyRootFilesystem: true
      volumes:
      - name: secrets
        secret:
          secretName: {{ .Values.oauth2Proxy.secretName }}
          items:
            - key: {{ .Values.oauth2Proxy.config.clientSecretKey }}
              path: client_secret
            - key: {{ .Values.oauth2Proxy.config.cookieSecretKey }}
              path: cookie_secret  
{{- end }}