quarkus.oidc.enabled=false
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/postgres?password=password&user=user
quarkus.datasource.jdbc.max-size=16

# HTTP Service Configuration
app.http.user-agent=FeedBox/1.0.0
app.http.timeout=30

# scheduler config
refresh.job.interval=1h

quarkus.native.additional-build-args=--initialize-at-run-time=com.apptasticsoftware.rssreader.AbstractRssReader
