quarkus.oidc.enabled=false

quarkus.smallrye-jwt.enabled=true
mp.jwt.verify.publickey.location=
mp.jwt.verify.issuer=NONE

sso.clientid=
sso.redirectUri=
sso.authServerUrl=

quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/postgres?password=password&user=user
quarkus.datasource.jdbc.max-size=16

# HTTP Service Configuration
app.http.user-agent=FeedBox/2.0.2-SNAPSHOT
app.http.timeout=30
# scheduler config
refresh.job.interval=1h
quarkus.native.additional-build-args=--initialize-at-run-time=com.apptasticsoftware.rssreader.AbstractRssReader
