quarkus.oidc.enabled=false
#quarkus.oidc.auth-server-url=https://authentik.0x2b.de/application/o/yarr/
#quarkus.oidc.client-id=3KIxUxUJ42z94xMdn4ku29XjBh7roLPrExbCoPtM
#quarkus.oidc.application-type=web-app
#quarkus.oidc.credentials.secret=xJDbScImfUzZMmTpdekop4568d4aKM31kzVe4J6ewFSunCOo9kDvK0wiOqqlYTdLJurfUECX86nMapK6ZShZdddasdfaWETRBasdftDrHAGR3Uh8MA1kU5GB4SWW10VaYR5o3xclbDWLOU2yzJPPdzzAbho
#quarkus.http.auth.permission.authenticated.paths=/api/*
#quarkus.http.auth.permission.authenticated.policy=authenticated
#quarkus.oidc.authentication.scopes=oidc,offline_access
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/postgres?password=password&user=user
quarkus.datasource.jdbc.max-size=16
# HTTP Service Configuration
app.http.user-agent=FeedBox/2.0.2-SNAPSHOT
app.http.timeout=30
# scheduler config
refresh.job.interval=1h
quarkus.native.additional-build-args=--initialize-at-run-time=com.apptasticsoftware.rssreader.AbstractRssReader
