name: "Test backend"

on:
  pull_request:
  push:
    branches-ignore:
      - "main"

concurrency:
  group: test-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - name: "checkout"
        uses: "actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1" # v7.0.1
      - name: "setup java"
        uses: "actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6" # v6.0.1
        with:
          java-version: "25"
          distribution: "temurin"
          cache: "maven"
      - name: "run maven tests"
        run: "mvn --no-transfer-progress test"
