on:
  push:
    branches-ignore:
      - master

jobs:
  test:
    runs-on: "ubuntu-latest" # java?
    steps:
      - name: "checkout"
        uses: "actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8" # v5
      - name: "setup java"
        uses: "actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165" # v5
        with:
          java-version: "25"
          distribution: "temurin"
      - name: "run maven tests"
        run: "mvn test"
